apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chronogram-secrets
  namespace: chronogram
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: replace-with-store
    kind: ClusterSecretStore
  target:
    name: chronogram-secrets
  data:
    - secretKey: api-key
      remoteRef:
        key: chronogram/api-key
    - secretKey: neo4j-password
      remoteRef:
        key: chronogram/neo4j-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chronogram-platform-secrets
  namespace: chronogram
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: replace-with-store
    kind: ClusterSecretStore
  target:
    name: chronogram-platform-secrets
  data:
    - secretKey: neo4j-password
      remoteRef:
        key: chronogram/platform/neo4j-password
    - secretKey: temporal-postgres-user
      remoteRef:
        key: chronogram/platform/temporal-postgres-user
    - secretKey: temporal-postgres-password
      remoteRef:
        key: chronogram/platform/temporal-postgres-password
    - secretKey: temporal-postgres-db
      remoteRef:
        key: chronogram/platform/temporal-postgres-db
